### DISCUSSION TITLE
How to deserialize nested tables in a Version Catalog like structure?

### DISCUSSION THREAD

**Discussion by WhosNickDoglio** [akuleshov7/ktoml#273] [Q&A]
Hello I'm back with a follow up of sorts to this #181

[Strixpyrrs solution ](https://github.com/orchestr7/ktoml/issues/181#issuecomment-1382608949) worked **great** for serializating a Version Catalog from a previous dependency managment system but now my team is playing around with breaking our Version Catalog down by codeowners and using ktoml to then generate a merged Catalog with all the dependencies so now I need to figure out deserializing it 😅 

I effectively want to be able to turn something like this

```toml
[versions]
androidx-activity-version = "1.8.2"
androidx-navigation = "2.7.7"

[plugins]
androidx-navigation-safeargs = { id = "androidx.navigation.safeargs", version.ref = "androidx-navigation" }
dependencyGuard = { id = "com.dropbox.dependency-guard", version = "0.5.0" }

[libraries]
androidx-activity-compose = { module = "androidx.activity:activity-compose", version.ref = "androidx-activity-version" }
androidx-annotation = { module = "androidx.annotation:annotation-jvm", version = "1.7.1" }
```

into the models in the original issue

```kotlin
@Serializable
data class VersionCatalog(
    val versions: Map<String, String>,
    val plugins: Map<String, Plugin>,
    val libraries: Map<String, Library>,
)

@Serializable(with = LibrarySerializer::class)
@TomlInlineTable
sealed interface Library {
    val module: String
}

@Serializable
@TomlInlineTable
data class InlineVersionLibrary(
    override val module: String,
    val version: String,
) : Library

@Serializable
@TomlInlineTable
data class RefVersionLibrary(
    override val module: String,
    val version: Version,
) : Library

@Serializable
@TomlInlineTable
data class Version(val ref: String)

@Serializable(with = PluginSerializer::class)
@TomlInlineTable
sealed interface Plugin {
    val id: String
}

@Serializable
@TomlInlineTable
data class RefVersionPlugin(override val id: String, val version: Version) : Plugin

@Serializable
@TomlInlineTable
data class InlineVersionPlugin(override val id: String, val version: String) : Plugin
```

But I'm running into a bunch of issues as I'm trying to update `LibrarySerializer` to support deserialization (Maybe related to #255)

I have something that _kinda_ works but it ends up being entirely string based and I lose any of the typing I was hoping for and was wondering if there was something obvious I was missing?

Error Message i've been seeing 

```
            You are trying to decode a nested Table plugins.androidx-navigation-safeargs with a <Map> type to some primitive type.
            For example: 
            [a]
              [a.b]
                  a = 2
                  
            should be decoded to Map<String, Map<String, Long>>, but not to Map<String, Long>
```
