### ISSUE TITLE
How to structure classes for Version Catalog inline versions and version references?

### ISSUE THREAD

**Issue by WhosNickDoglio** [akuleshov7/ktoml#181]
Hello! I've started using this project recently to auto-generate Version Catalogs from an internal dependency management tool and ran into an issue on how to structure my models to support both inline versions and version refs. So something like the following: 

```toml
detekt-formatting = { module = "io.gitlab.arturbosch.detekt:detekt-formatting", version.ref = "detekt" }
detekt-compose = { module = "com.twitter.compose.rules:detekt", version = "0.0.26" }
```

A couple things I've tried:
- Starting with a `GradleLibrary` interface and then making subclasses with one for inline versions and the other having versions references. This lead to the `type` being added to the TOML file.
- Having two optional, nullable params on my `GradleLibrary` that take a version and version.ref but with both annotated with `@SerialName("version")`, kotlinx.serialization labels that an error.
- Similar to the above I added two optional, nullable params to my `GradleLibrary` class both strings, one called `version` and another called `versionRef` but annotated with `@SerialName("version.ref")` which generates a Version Catalog with all the `version.ref`s in quotation marks 😅

Any suggestions for how to structure my models to achieve this? (Sorry if this is the wrong place to ask this, feel free to move it to the discussions section in case it makes more sense there)
