### ISSUE TITLE
Invalid call to getNeighbourNodes

### ISSUE THREAD

**Issue by Wavesonics** [akuleshov7/ktoml#189]
Getting a crash:
`by: com.akuleshov7.ktoml.exceptions.InternalAstException: Invalid call to getNeighbourNodes() for TomlFile node`

Parsing this file:
```toml
email = "test5"
url = "http://localhost:8080"
deviceId = "50694ed7-a93f-4713-9e55-4d512ce2e4db"
bearerToken = "a8DkRGThvz13cmVubFdgX0CsoLfAtXcBvyxiKCPY34FEt3UDmPBkMKFRk4iKRuRp"
refreshToken = "20NSBgKB2B9C2u2toAuiPqlaZgfEWJ4m50562YK9w575SNt31CWrjcpwqeiDCYhZ"
```

Into this class:
```kotlin
@Serializable
data class ServerSettings(
    val email: String,
    val url: String,
    val deviceId: String,
    val bearerToken: String?,
    val refreshToken: String?,
)
```
